# Generated by Django 2.0.4 on 2018-04-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneywalletapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Cust',
            new_name='Custdetail',
        ),
    ]
