# Generated by Django 2.0.4 on 2018-04-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneywalletapp', '0002_auto_20180405_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Custdetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
